### PR TITLE
Add Contact Form in contact page #28

### PR DESCRIPTION
**Pull request by albert18**
For someone to able To send emails using SMTP in the contact page.

Note: I was using VS 2017 .Net Core 2.0. I notice that you're using 2.1 you can exclude or change the file if you want.

To test this you must edit the contact in Home Controller and add your GMAIL email and password.

### CODE REVIEW

**Comment by n3ug** [comment]
Thanks for the submission.   Sorry but I am travelling this week will review next week

**Comment by albert18** [comment]
Awesome no worry, If you have a question just let me know.


Thanks

Albert

________________________________

**Comment by n3ug** [comment]
@albert18 sorry again for the delay.  I reviewed the pull request, and thank you VERY much for submitting the code, however, in keeping with .net core principles I would prefer to have email implemented as a service that would be configured using appsettings.json (or in a key vault) rather than hard coded in the HomeController. You would then register the service in the startup class. 

This would allow us to use dependency injection to inject an instance of our email service at startup to the controller in the same way we use DI to inject a repository service into the controller.  we could then switch email providers in the future, or provide options for multiple email services (SendGrid, etc), or even develop a mock email service for unit testing. 

So, in the startup.cs file you would configure the email service in the ConfigureServices() method with something like

`services.AddTransient<IEmailService, EmailService>( );`

and then when starting up a new HomeController() you would inject the email service

`private IEmailService _email;`
`public HomeController(IEmailService, email)  {`
`      _email = email;`
`}`


and finally in the HomeController, when time to send an email, you would use the injected instance to do so
`_email.Send(msg);`

If you want to give it another try, please feel free to do so, and don't hesitate to contact me with any questions.

**Comment by albert18** [comment]
Steve,
Absolutely your right it's better to put sensitive information in the vault. I'll take a look it again when I get chance and I'll update the code.

Thanks

**Pull request closed without merging**
